<?php
/**
 * Digit Software Solutions.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 *
 * @category  Dss
 * @package   Dss_PreSelectShippingPayment
 * @author    Extension Team
 * @copyright Copyright (c) 2024 Digit Software Solutions. ( https://digitsoftsol.com )
 */
?>

<?php
/**
 * Multi Shipping Checkout Template
 *
 * @var $block Dss\PreSelectShippingPayment\Block\ConfigMenthod
 *
 */
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Dss_PreSelectShippingPayment/js/checkout_process": {
                "defaultShipping": "<?= /* @noEscape */ $escaper->escapeHtml($block->getShippingDefault()); ?>",
                "defaultPayment" : "<?= /* @noEscape */ $escaper->escapeHtml($block->getPaymentDefault());?>",
                "positionShipping" : "<?= /* @noEscape */ $escaper->escapeHtml($block->getShippingPosition()); ?>",
                "positionPayment" : "<?= /* @noEscape */ $escaper->escapeHtml($block->getPaymentPosition()); ?>"
            }
        }
    }
</script>
